# Generated by Django 4.0.2 on 2022-03-25 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentences',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('sentence', models.TextField()),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
